@startuml

skinparam componentStyle rectangle

actor User
database myList #lightblue
database database #lightblue

component UI #green
component Parser #red
component Main #gray
component Storage #pink
component Command #gold

User -down.-> UI
UI -right-> Parser

Main -down-> Parser
Main -down-> UI
Main -up-> Storage

Command -down-> Storage
Parser -right-> Command

Command -right.-> database
Storage -right.-> myList

@enduml
