@startuml
hide footbox

actor CEG_Student
participant ":UI" #green
participant ":Parser" #gold
participant ":Command" #pink
participant ":Storage" #lightblue

CEG_Student -> ":UI" : "delete 1"
activate ":UI" #green

":UI" -> ":Parser" : execute("delete 1")
activate ":Parser" #gold

":Parser" -> ":Command" : allCourses.remove(index);
activate ":Command" #pink

":Command" -> ":Storage" : saveAllCourses(allCourses);
activate ":Storage" #lightblue

":Storage" -> ":Storage" : Save to mylist.json
activate ":Storage" #lightblue

":Storage" --> ":Storage"
deactivate ":Storage"
":Storage" --> ":Command"
deactivate ":Storage"

":Command" --> ":Parser"
deactivate ":Command"

":Parser" --> ":UI"
deactivate ":Parser"

":UI" --> CEG_Student
deactivate ":UI"

@enduml
