@startuml
hide footbox

actor CEG_Student
participant ":UI" #green
participant ":Parser" #gold
participant ":Command" #pink
participant ":Storage" #lightblue

CEG_Student -> ":UI" : "delete 1"
activate ":UI" #green

":UI" -[#green]> ":Parser" : execute("delete 1")
activate ":Parser" #gold

":Parser" -[#gold]> ":Command" : allCourses.remove(index);
activate ":Command" #pink

":Command" -[#pink]> ":Storage" : saveAllCourses(allCourses);
activate ":Storage" #lightblue

":Storage" -[#lightblue]> ":Storage" : Save to mylist.json
activate ":Storage" #lightblue

":Storage" -[#lightblue]-> ":Storage"
deactivate ":Storage"
":Storage" -[#lightblue]-> ":Command"
deactivate ":Storage"

":Command" -[#pink]-> ":Parser"
deactivate ":Command"

":Parser" -[#gold]-> ":UI"
deactivate ":Parser"

":UI" -[#green]-> CEG_Student
deactivate ":UI"

@enduml
