@startuml
actor CEG_Student
participant ListSchoolCommand
participant Command

CEG_Student -> ListSchoolCommand: execute(userInput)
activate ListSchoolCommand

ListSchoolCommand -> Command: createJsonObject()
activate Command

Command --> ListSchoolCommand: JsonObject
deactivate Command

ListSchoolCommand -> ListSchoolCommand: displaySchoolList(JsonObject)
activate ListSchoolCommand

ListSchoolCommand --> ListSchoolCommand: List of school names
deactivate ListSchoolCommand

ListSchoolCommand --> CEG_Student: Print results
deactivate ListSchoolCommand
@enduml
