@startuml

hide footbox

actor CEG_Student
participant ":ListSchoolCommand" as ListSchoolCommand
participant ":Command" as Command

CEG_Student -> ListSchoolCommand: execute (userInput:String)
activate ListSchoolCommand

ListSchoolCommand -> Command: createJsonObject()
activate Command

Command --> ListSchoolCommand: JsonObject
deactivate Command

ListSchoolCommand -> ListSchoolCommand: displaySchoolList (jsonObject:JsonObject)
activate ListSchoolCommand

ListSchoolCommand --> ListSchoolCommand
deactivate ListSchoolCommand

ListSchoolCommand --> CEG_Student
deactivate ListSchoolCommand
@enduml
