@startuml

skinparam componentStyle rectangle

component PersonalTrackerCommand <<abstract>> #skyblue
component CheckInformationCommand <<abstract>> #lime
component ListSchoolsCommand #lightblue
component DeleteCoursesCommand #lightgreen
component Command <<abstract>> #red

PersonalTrackerCommand -up-|> Command
CheckInformationCommand -up-|> Command

ListSchoolsCommand -up-|> CheckInformationCommand
DeleteCoursesCommand -up-|> PersonalTrackerCommand

@enduml
