@startuml
participant "TransactionList" as TL
participant "Stream<Transaction>" as Stream
participant "List<Transaction>" as Result

TL -> Stream : transactions.stream()
activate Stream
Stream -> Stream : filter(transaction instanceof Expense)
Stream -> Stream : map(transaction -> (Expense) transaction)
Stream -> Stream : filter(expense.getCategory().equals(category))
Stream -> Result : collect(Collectors.toList())
Result --> Stream
Stream --> TL : Result
@enduml
