@startuml
class ":Question" {
    - text : String
    + Question(String text)
    + getText() : String
    + checkAnswer(String userAnswer) : boolean
    + printOptions() : void
    + toString() : String
}

class TrueFalse {
    - correctAnswer : boolean
    + TrueFalse(String questionText, boolean correctAnswer)
    + checkAnswer(String userAnswer) : boolean
    + printOptions() : void
    + toString() : String
}

TrueFalse --|> Question : extends
@enduml
