@startuml
skinparam backgroundColor #FFFFFF
skinparam sequence {
    ArrowColor #2C3E50
    LifeLineBorderColor #2C3E50
    ParticipantBorderColor #2C3E50
    ParticipantBackgroundColor #FFFFFF
}
hide footbox

participant "<<Class>> \n Storage" as S
participant ":CategoryFacade" as CF
participant ":CategoryStorage" as CS
participant ":CategoryTracker" as CT
participant ":CategoryFilter" as CFilt
participant ":ExpenseList" as EL

S -> CF: call interface's method
CF -> CT: clear current tracker
CT --> CF: return
CF -> EL: obtain expense list
EL --> CF: return expense list
CF -> CS: populate tracker using expense list
CS --> CF: return tracker
CF -> CS: call load method
CS --> CF: return
CF -> CFilt: populate maxheaps to sort exceeding and nearing categories
CFilt --> CF: return
CF -> CFilt: display categories with a total that exceeded the limit
CFilt --> CF: return
CF -> CFilt: display categories with a total that is nearing the limit
CFilt --> CF: return
CF --> S: return

@enduml
