@startuml
skinparam backgroundColor #FFFFFF
skinparam sequence {
    ArrowColor #2C3E50
    LifeLineBorderColor #2C3E50
    ParticipantBorderColor #2C3E50
    ParticipantBackgroundColor #FFFFFF
}
hide footbox

participant ":EditCommand" as EC
participant ":CategoryFacade" as CF
participant ":CategoryTracker" as CT
' participant ":CategoryData" as CD

EC -> CF: call interface's method
CF -> CT: call relevant method
CT -> CT: update tracker with new increased/decreased totals
CT --> CF:
CF --> EC:

@enduml
