@startuml
skinparam classAttributeIconSize 0
hide circle

class "{abstract}\nCommand" {
    +argumentsMap: HashMap<String, String>
    +Command(HashMap<String, String>)
    +execute(expenseList : ExpenseList, categoryFacade : CategoryFacade, recurringExpenseList : RecurringExpenseList) {abstract}
    +isExit(): boolean
}

class ExpenseList {
    +addExpense(price: Float, description: String, category: String): void
    +addExpense(price: Float, description: String, category: String, dateAdded: LocalDate): void
    +editExpenses(index: int): void
    +deleteExpense(index: int): void
    +listByFilter(category: String, from: String, to: String): ArrayList<Expense>
}

"{abstract}\nCommand" .down.> " 1   " ExpenseList
@enduml
