@startuml
!include style.puml
hide footbox

participant ":Main" as main
participant ":AddCommand" as command COMMAND_COLOUR
participant ":EventList" as eventList EVENT_COLOUR

main -> command : execute()
activate command COMMAND_COLOUR

alt participantName == null
    ref over command, eventList: Add event to event list
else participantName != null
    ref over command, eventList: Add participant to event list

end

return


@enduml