@startuml
hide footbox

actor CEG_Student
!include .SequenceDiagram.config
participant ":AddCoursesCommand" as AddCoursesCommand
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":CourseValidator" as CourseValidator
participant ":Command" as Command
participant ":Course" as Course
participant ":Storage" as Storage




CEG_Student -> AddCoursesCommand: execute (userInput:String, storage:Storage)
activate AddCoursesCommand

AddCoursesCommand -> Command: createJsonObject()
activate Command

Command --> AddCoursesCommand: jsonObject:JsonObject
deactivate Command

AddCoursesCommand -> AddCoursesCommand:trimString(userInput: String)
activate AddCoursesCommand
return description: String

AddCoursesCommand -> AddCoursesCommand:parseAddCommand(input: String)
activate AddCoursesCommand
return descriptionSubstring: String[]

AddCoursesCommand -> Parser: parsePUAbbreviations(pu: String)
activate Parser
return parsed pu string

AddCoursesCommand -> CourseValidator: isValidInput(...)
activate CourseValidator
return isValidInput: Boolean

alt isValidInput
AddCoursesCommand -> Course **: new Course(...)
activate Course
Course --> AddCoursesCommand : returns Course
deactivate

AddCoursesCommand -> Storage :addCourse(courseToStore: Course)

else else
AddCoursesCommand -> Ui: print error message
activate Ui
Ui --> AddCoursesCommand: display error message
deactivate Ui

end
return

@enduml
