@startuml
participant ":CreateDayProgrammeCommand" as CreateDayProgrammeCommand
participant ":ProgrammeList" as ProgrammeList
participant ":Programme" as Programme

-> CreateDayProgrammeCommand : execute()
activate CreateDayProgrammeCommand

CreateDayProgrammeCommand -> ProgrammeList : getProgramme(programmeIndex)
activate ProgrammeList

opt Programme exists
    ProgrammeList --> CreateDayProgrammeCommand : selected Programme
    deactivate ProgrammeList

    CreateDayProgrammeCommand -> Programme : insertDay(createdDay)
    activate Programme

    Programme --> CreateDayProgrammeCommand : inserted Day
    deactivate Programme
end

<-- CreateDayProgrammeCommand : inserted Day
deactivate CreateDayProgrammeCommand
@enduml