@startuml
participant ":CreateDayCommand" as CreateDayCommand #cc88cc
participant ":ProgrammeList" as ProgrammeList #ffbb77
participant ":Programme" as Programme #ffbb77



activate CreateDayCommand
-> CreateDayCommand : execute()

CreateDayCommand -> ProgrammeList : getProgramme(programmeIndex)
activate ProgrammeList

ProgrammeList --> CreateDayCommand : selected Programme
deactivate ProgrammeList

CreateDayCommand -> Programme : insertDay(createdDay)
activate Programme

Programme --> CreateDayCommand :  inserted day
deactivate Programme

<-- CreateDayCommand
deactivate CreateDayCommand
@enduml
