@startuml
participant ":CreateExerciseCommand" as AddExerciseCommand
participant ":ProgrammeList" as ProgrammeList
participant ":Programme" as Programme
participant ":Day" as Day

-> AddExerciseCommand : execute()
activate AddExerciseCommand

AddExerciseCommand -> ProgrammeList : getProgramme(programmeIndex)
activate ProgrammeList

opt Programme exists
    ProgrammeList --> AddExerciseCommand : selected Programme
    deactivate ProgrammeList

    AddExerciseCommand -> Programme : getDay(dayIndex)
    activate Programme

    opt Day exists
        Programme --> AddExerciseCommand : selected Day
        deactivate Programme

        AddExerciseCommand -> Day: insertExercise(createdExercise)
        activate Day
        Day --> AddExerciseCommand: inserted Exercise
        deactivate Day
    end
end

<-- AddExerciseCommand  : insert Exercise
deactivate AddExerciseCommand
@enduml