@startuml
!include style.puml
hide footbox

participant ":AddCommand" as command COMMAND_COLOUR
participant ":EventList" as eventList EVENT_COLOUR
participant "eventList:ArrayList<Event>" as list EVENT_COLOUR
participant "newEvent:Event" as event EVENT_COLOUR

group sd Add event
    activate command COMMAND_COLOUR
    command -> eventList : addEvent(eventName, time, venue, priority)
    activate eventList EVENT_COLOUR

    eventList -> eventList : getEventByName(eventName)
    activate eventList EVENT_COLOUR

    return :Event

    alt event already present
        eventList --> command : :DuplicateDataException
    else else

        create event
        eventList -> event : Event(eventName, venue, time, priority)
        activate event EVENT_COLOUR

        return

        eventList -> list : add(newEvent : Event)
        activate list EVENT_COLOUR

        return

        return
    end

end

@enduml