@startuml
!include style.puml
hide footbox

participant ":AddCommand" as command  
participant ":EventList" as eventList  

group sd Add participant
    activate command  
    command -> eventList : addParticipantToEvent(participantName,\n participantEmail, eventName)
    activate eventList  

    eventList -> eventList : getEventByName(eventName)
    activate eventList  

    return event:Event

    alt event not found
        eventList --> command : Invalid event
    else else
        ref over eventList : Add participant to event
    end

    return
end
@enduml