@startuml

!include style.puml
skinparam ArrowFormatStyle plain
scale 0.5

scale 1.5

actor User
participant ":MediTask" as MediTask MAIN_COLOR
participant ":Parser" as Parser PARSER_COLOR
participant ":AddParser" as AddParser PARSER_COLOR
participant ":AddPatientCommand" as AddPatientCommand COMMAND_COLOR
participant ":Hospital" as hospital DATA_COLOR

User -> MediTask : enter "add John Doe [tag]"
activate MediTask
MediTask -> Parser : parseCommand("add John Doe [tag]", currentState)
activate Parser
Parser -> AddParser : execute("add John Doe [tag]", currentState)
deactivate Parser
activate AddParser
AddParser -> AddPatientCommand : new AddPatientCommand(name, tag)
deactivate AddParser
activate AddPatientCommand

alt Name is null or empty
    AddPatientCommand --> MediTask : throw AssertionError
else Name is not null or empty
    AddPatientCommand -> hospital : isDuplicatePatient(name)
    alt Duplicate patient
        AddPatientCommand --> MediTask : return "This patient already exists in the hospital"
        MediTask --> User : Display "This patient already exists in the hospital"
    else No duplicate
        AddPatientCommand -> hospital : addPatient(name, tag)
        alt tag is not null or empty
            AddPatientCommand --> MediTask : return "New patient added: John Doe [tag]"
            MediTask --> User : Display "New patient added: John Doe [tag]"
        else tag is null or empty
            AddPatientCommand --> MediTask : return "New patient added: John Doe"
            MediTask --> User : Display "New patient added: John Doe"
        end
    end
end
deactivate AddPatientCommand
destroy AddPatientCommand
deactivate MediTask

@enduml
