@startuml
!include style.puml
hide footbox

participant ":AddCommand" as command COMMAND_COLOUR
participant ":EventList" as eventList EVENT_COLOUR

group sd Add participant
    activate command COMMAND_COLOUR
    command -> eventList : addParticipantToEvent(String, String, String, String)
    activate eventList EVENT_COLOUR

    eventList -> eventList : getEventByName(String)
    activate eventList EVENT_COLOUR

    return event:Event

    alt event not found
        eventList --> command : Invalid event
    else else
        ref over eventList : Add participant to event
    end

    return
end
@enduml