@startuml
!include style.puml
hide footbox

participant ":EventList" as eventList  
participant ":Event" as event  
participant "participant:Participant" as participant  
participant "participantList:ArrayList<Participant>" as participantList  

group sd Add participant to event
    activate eventList  

    eventList -> event : addParticipant(participantName, participantEmail)
    activate event  

    event -> event : getParticipantByName(participantName, participantEmail)
    activate event  
    return :Event

    alt participant already present
        event --> eventList:throws DuplicateDataException
    else else
        event -> participant : Participant(participantName, participantEmail)
        activate participant  
        return participant:Participant

        event -> participantList : add(participant)
        activate participantList  
        return
    end

    return
end
@enduml