@startuml

Main -> Parser: add -p John Doe -e Meeting -n 92561352 -email johndoe@example.com
activate Parser
Parser -> AddCommand: new AddCommand("John Doe", "12345678", "johndoe@example.com", "Meeting")
activate AddCommand
AddCommand -> EventList: addParticipantToEvent("John Doe", "12345678", "johndoe@example.com", "Meeting")
activate EventList
EventList --> AddCommand
deactivate EventList
AddCommand --> Parser
deactivate AddCommand
Parser --> Main
deactivate Parser

@enduml