@startuml
!include style.puml
hide footbox

Participant ":Main" as main
Participant ":Ui" as ui UI_COLOUR
Participant ":Storage" as storage STORAGE_COLOUR
Participant ":EventList" as events EVENT_COLOUR

main -> ui : greetUser()
activate ui UI_COLOUR
return

ref over main, storage, events : Loading of events list

main -> main : runCommandLoop()
activate main

loop isGettingCommands
ref over main, events :  Command parsing and execution
ref over main, storage, events : Saving of events list
end

return

@enduml