@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam classBackgroundColor White
skinparam classBorderColor Black

rectangle User {
}

rectangle Exceptions {
}

rectangle Storage {
}

rectangle FitTrack {
}

rectangle Parser {
}

rectangle Ui {
}

rectangle Miscellaneous {
}

FitTrack  -->  Parser
FitTrack  -->  Ui
FitTrack  -->  Storage
FitTrack  -->  User

Parser  -->  Miscellaneous
Parser  -left->  User
Parser  -right->  Ui

Ui  -->  Miscellaneous

Storage  -->  Miscellaneous
Storage -> User
Miscellaneous  -->  User

@enduml
