@startuml
' Use right-angle straight lines for relationships
skinparam linetype ortho
hide circle
skinparam classAttributeIconSize 0
skinparam classBackgroundColor White
skinparam classBorderColor Black

' Define classes
class FitTrack {
    -sessionList : ArrayList<TrainingSession>
}

class Parser {
    -command : String
    -description : String
    -currentTime : LocalDateTime
    +parse()
}

class Ui {
    +printGreeting()
    +printUser()
    +printHelp()
    +printAddedSession()
    +printDeletedSession()
    +printSessionList()
    +printSessionView()
    +printSessionCount()
    +printUnrecognizedInputMessage()
}

class Storage {
    +initialiseSaveFile()
    +loadSaveFile()
    +updateSaveFile()
}

class TrainingSession {
    -description : String
    -sessionDateTime : LocalDateTime
    -user : User
    -exerciseStations : Map<Exercise, ExerciseStation>
    -initialiseExerciseStations()
    +editExercise()
    +getSessionDescription()
    +viewSession()
}

class User {
    -gender : Gender
    -age : int
    +setGender()
    +setAge()
    +getGender()
    +getAge()
}

enum Exercise <<enumeration>> {
    PULL_UP
    SHUTTLE_RUN
    SIT_AND_REACH
    SIT_UP
    STANDING_BROAD_JUMP
    WALK_AND_RUN
}

class FitTrackLogger {
    +setupLogger()
}

class ExerciseStation {
    +getName()
    +toString()
}

class Calculator {
    -getPointsFromTable()
    -addAgeSubTable()
    -addAllTables()
    +calculatePoints()
}

' Define relationships with right-angle arrows
FitTrack "1" --> "1" Storage : uses >
FitTrack "1" --> "1" FitTrackLogger : uses >
FitTrack "1" --> "1" User : creates >
FitTrack "1" --> "1" Parser : uses >
FitTrack "1" --> "1" Ui : uses >

Parser "1" --> "1" Ui : uses >
Parser "1" --> "1" User : manages >
Parser "1" --> "*" TrainingSession : manages >
Parser "1" --> Exercise : references >

Ui "1" -> "1" User : displays >
Ui "1" --> "*" TrainingSession : displays >

Storage "1" --> "*" TrainingSession : manages >
Storage "1" --> "1" FitTrackLogger : uses >

TrainingSession "*" ---> "1" User : belongs to >
TrainingSession "*" --> Exercise : references >
TrainingSession "1" --> "6" ExerciseStation : contains >

ExerciseStation "1" --> "1" Calculator : uses >

@enduml
