@startuml
!include style.puml
hide footbox

participant ":Main" as main
participant ":Ui"  as ui 
participant ":Parser"  as parser 
participant ":XYZCommand" as xyzCommand 

activate main

main -> ui : getCommand()
activate ui 

return userCommandText:String

main -> parser : parseCommand(userCommandText)
activate parser 

create xyzCommand
parser -> xyzCommand : XYZCommand(...)
activate xyzCommand 
xyzCommand --> parser
deactivate xyzCommand

parser --> main : command:Command
deactivate parser

main -> xyzCommand : setData(events)
activate xyzCommand 
xyzCommand --> main
deactivate xyzCommand

main -> xyzCommand : execute()
activate xyzCommand 
xyzCommand --> main
deactivate xyzCommand

main -> ui : showOutputToUser(command)
activate ui 

ui -> xyzCommand : getMessage()
activate xyzCommand 
xyzCommand --> ui
deactivate xyzCommand

ui --> main
deactivate ui
@enduml