@startuml
!include .ClassDiagram.config
left to right direction

class Command as "{abstract} \nCommand"{
    +createJsonObject(): JsonObject
}

class CheckInformationCommand as "{abstract} \nCheckInformationCommand" extends Command {
    +execute(userInput: String): void ABSTRACT
}

class PersonalTrackerCommand as "{abstract} \nPersonalTrackerCommand" extends Command {
    +execute(userInput: String, storage: Storage): void ABSTRACT
}

class FilterCoursesCommand extends CheckInformationCommand

class HelpCommand extends CheckInformationCommand

class ListCommandsCommand extends CheckInformationCommand

class ListSchoolCommand extends CheckInformationCommand

class ListUniCoursesCommand extends CheckInformationCommand

class ObtainContactsCommand extends CheckInformationCommand

class AddCoursesCommand extends PersonalTrackerCommand

class DeleteCoursesCommand extends PersonalTrackerCommand

class ListPersonalTrackerCommand extends CheckInformationCommand

ListPersonalTrackerCommand --> "storage 1" Storage
Storage : +loadAllCourses(): void

AddCoursesCommand --> "courseValidator 1" CourseValidator
CourseValidator : +isValidInput(...): boolean
AddCoursesCommand ..> UI
UI : +printAddMessage(): void

DeleteCoursesCommand ..> UI
UI : +printDeleteMessage(): void

@enduml
