@startuml
participant ":Main" as Main
participant ":CopyCommand" as CC
participant ":EventList" as EL
participant "eventFrom :Event" as SourceEvent
participant "eventTo :Event" as DestEvent

Main -> CC: execute()
activate CC

CC -> EL: getEventByName(copyTo)
activate EL
EL --> CC: return eventTo
deactivate EL

CC -> EL: getEventByName(copyFrom)
activate EL
EL --> CC: return eventFrom
deactivate EL

opt Both Events Found
    CC -> SourceEvent: getParticipantList()
    activate SourceEvent
    SourceEvent --> CC: return participantList
    deactivate SourceEvent

    opt Participant List Not Empty
        CC -> DestEvent: setParticipantList(participantList)
        activate DestEvent
        DestEvent --> CC
        deactivate DestEvent
    end opt

end opt

CC --> Main: Display copy result message
deactivate CC

@enduml