@startuml
hide footbox
!include .SequenceDiagram.config
participant ":AddCoursesCommand" as AddCoursesCommand
participant ":CourseValidator" as CourseValidator

activate AddCoursesCommand

AddCoursesCommand -> CourseValidator:isValidInput(nusCourseInput: String, pu: String, puCourseInput: String, jsonObject: JsonObject)
activate CourseValidator

CourseValidator -> CourseValidator:getPUCourseList
activate CourseValidator

alt matchPu != null
CourseValidator -> CourseValidator: get JsonArray for Partner University
else
CourseValidator -> CourseValidator:displayPartnerUniversities()
activate CourseValidator
deactivate
CourseValidator -> CourseValidator: throw IllegalArgumentException
end
return courses: JsonArray


CourseValidator -> CourseValidator: isValidCourseMapping
activate CourseValidator


loop for each course in courses JsonArray
CourseValidator -> CourseValidator:getJsonObject(course)
CourseValidator -> CourseValidator:get puCourseCode from JsonArray
CourseValidator -> CourseValidator:get nusCourseCode from JsonArray

opt puCourseCode == puCourseCodeInput && nusCourseCode == nusCourseCodeInput
    CourseValidator --> AddCoursesCommand: true: Boolean
end

end
  CourseValidator --> CourseValidator: displayAvailableMappings()
  CourseValidator --> AddCoursesCommand: false: Boolean
deactivate

deactivate
@enduml