@startuml

!include style.puml
skinparam ArrowFormatStyle plain
skinparam style strictuml

actor User
participant ":MediTask" as MediTask MAIN_COLOR
participant ":Parser" as Parser PARSER_COLOR
participant ":DeleteParser" as DeleteParser PARSER_COLOR
participant ":DeletePatientCommand" as DeletePatientCommand COMMAND_COLOR
participant ":Hospital" as Hospital DATA_COLOR

User -> MediTask : "delete <index>"
activate MediTask

MediTask -> Parser : parseCommand(input, state)
activate Parser

Parser -> DeleteParser : execute(input, state)
activate DeleteParser
create DeletePatientCommand
DeleteParser -> DeletePatientCommand : new DeletePatientCommand(index)
activate DeletePatientCommand

DeletePatientCommand -> Hospital : getPatient(index)
activate Hospital

alt Index valid
    Hospital --> DeletePatientCommand : Patient
    DeletePatientCommand -> Hospital : deletePatient(index)
    DeletePatientCommand --> DeleteParser : "Deleted patient: <patient name>"
    deactivate DeletePatientCommand

    DeleteParser --> Parser : "Result message"
    deactivate DeleteParser

    Parser --> MediTask : "Result message"
    deactivate Parser

    MediTask --> User : Display result message
    deactivate MediTask
else Index invalid
    Hospital --> DeletePatientCommand : throw Exception
    activate DeletePatientCommand
    deactivate Hospital
    DeletePatientCommand --> DeleteParser : "Patient not found in the list!"
    deactivate DeletePatientCommand
    activate DeleteParser
    DeleteParser --> Parser : "Error message"
    deactivate DeleteParser
    activate Parser
    Parser --> MediTask : "Error message"
    deactivate Parser
    activate MediTask
    MediTask --> User : Display error message
    deactivate MediTask
end

destroy DeletePatientCommand

@enduml
