@startuml
actor User
participant SpendSwift
participant Parser
participant ExpenseManager
participant TrackerData
participant InputParser
participant ErrorMessage
participant SuccessMessage
participant Expense

User -> SpendSwift : input("delete-expense 2")
SpendSwift -> Parser : parseCommand(input, trackerData)

activate Parser
Parser -> ExpenseManager : deleteExpenseRequest(input, expenseManager, trackerData)

activate ExpenseManager
ExpenseManager -> InputParser : parseIndex(input)
InputParser --> ExpenseManager : Return expenseIndex

alt Invalid Index
    ExpenseManager -> ErrorMessage : printInvalidIndex()
    deactivate ExpenseManager
    deactivate Parser
else Valid Index
    ExpenseManager -> TrackerData : getExpenses()
    TrackerData --> ExpenseManager : Return list of expenses

    alt Index Out of Bounds
        ExpenseManager -> ErrorMessage : printOutOfBoundsIndex()
        deactivate ExpenseManager
        deactivate Parser
    else Valid Index in Range
        ExpenseManager -> ExpenseManager : deleteExpense(trackerData, expenseIndex)

        activate ExpenseManager
        ExpenseManager -> TrackerData : getExpenses()
        TrackerData --> ExpenseManager : Return list of expenses

        ExpenseManager -> Expense : Remove expense at expenseIndex
        Expense --> ExpenseManager : Return removedExpense

        ExpenseManager -> SuccessMessage : printDeleteExpense(removedExpense)
        deactivate ExpenseManager
    end
end
deactivate ExpenseManager
deactivate Parser
@enduml
