@startuml
' Step 2: User executes delete command
title Step 3: User identifies and deletes Exercise

state ProgrammeList {
  state "p1:Programme" as P1 {
    state "d1:Day" as D1 {
      state "e1:Exercise" as E1
      state "e2:Exercise" as E2
    }
    state "d2:Day" as D2 {
      state "e3:Exercise" as E3
    }
  }
}

note right of E1
  Exercise1 has been
  identified for deletion
end note


' Current pointer indicator
state "DeleteExericseCommand" as CS
CS -> E1
@enduml