@startuml
start

:User executes command;

if (command type) then (prog edit)
  if (subcommand type) then (edit day)
    :Execute day edit;
  else (eidt exercise)
    :Execute exercise edit;
  endif
  :Retrieve updated model;

  :Create CommandResult;
endif

:Return result to User;

stop
@enduml