@startuml
participant ":EditExerciseCommand" as AddExerciseCommand #cc88cc
participant ":ProgrammeList" as ProgrammeList #ffbb77
participant ":Programme" as Programme #ffbb77
participant ":Day" as Day #ffbb77
participant ":Exercise" as Exercise #ffbb77


activate AddExerciseCommand
-> AddExerciseCommand : execute()

AddExerciseCommand -> ProgrammeList : getProgramme(programmeIndex)
activate ProgrammeList
ProgrammeList --> AddExerciseCommand : selected Programme
deactivate ProgrammeList

AddExerciseCommand -> Programme : getDay(dayIndex)
activate Programme
Programme --> AddExerciseCommand : selected Day
deactivate Programme

AddExerciseCommand -> Day: getExercise(exerciseIndex)
activate Day
Day --> AddExerciseCommand: selected Exercise
deactivate Day

AddExerciseCommand -> Exercise: updateExercise(update)
activate Exercise
AddExerciseCommand <-- Exercise: updated Exercise
deactivate Exercise

<-- AddExerciseCommand
deactivate AddExerciseCommand
@enduml
