@startuml
 hide footbox

 participant ":EditParticipantCommand" as editCommand
 participant ":EventList" as eventList
 participant ":Event" as event

 [-> editCommand : execute()
 activate editCommand

 editCommand -> eventList : editParticipant(participantName, participantEmail, eventName)
 activate eventList

 loop for each event in eventList
     eventList -> event : getEventName()
     activate event
     event --> eventList : eventName:String
     deactivate event

     opt eventName matches
         eventList -> event : updateParticipant(participantName, participantEmail)
         activate event
         event --> eventList : updated
         deactivate event
         eventList --> editCommand : :boolean
     end

end


return :boolean

return

@enduml