@startuml
' Step 2: User executes delete command
title Step 4: DeleteExerciseCommand retrieves deleted Exercise

state ProgrammeList {
  state "p1:Programme" as P1 {
    state "d1:Day" as D1 {
      state "e2:Exercise" as E2
    }
    state "d2:Day" as D2 {
      state "e3:Exercise" as E3
    }
  }
}


state DeleteExerciseCommand {
    state "e1:Exercise"
}
@enduml