@startuml
hide footbox

participant ":FilterCommand" as FC

[-> FC: execute()

create participant "FilteredEventList :EventList" as FEL
activate FC
FC -> FEL: new EventList()
activate FEL
FEL --> FC
deactivate FEL

alt filter by name
    FC -> FC : filterEventsByName()
    activate FC
    FC -> FEL: filterByName(...)
    activate FEL
    FEL --> FC: return filtered list
    deactivate FEL
    FC --> FC : :String
    deactivate FC
else filter by date
        FC -> FC : filterEventsByDate()
        activate FC
        FC -> FEL: filterByDate(...)
        activate FEL
        FEL --> FC: return filtered list
        deactivate FEL
        FC --> FC : :String
        deactivate FC
else filter by time
    FC -> FC : filterEventsByTime()
    activate FC
    FC -> FEL: filterByTime(...)
    activate FEL
    FEL --> FC: return filtered list
    deactivate FEL
    FC --> FC : :String
    deactivate FC
else filter by date-time
        FC -> FC : filterEventsByDateTime()
        activate FC
        FC -> FEL: filterByDateTime(...)
        activate FEL
        FEL --> FC: return filtered list
        deactivate FEL
        FC --> FC : :String
        deactivate FC
else filter by priority
    FC -> FC: filterEventsByPriority()
    activate FC
    FC -> FEL: filterByPriority(...)
    activate FEL
    FEL --> FC: return filtered list
    deactivate FEL
    FC --> FC : :String
    deactivate FC
end alt

return Display FilteredEventList and filter result message

destroy FEL

@enduml