@startuml
'https://plantuml.com/sequence-diagram

!include style.puml
skinparam ArrowFormatStyle plain
skinparam style strictuml

actor User
participant Parser PARSER_COLOR
participant FindParser PARSER_COLOR
participant Find PARSER_COLOR
participant FindPatientCommand PARSER_COLOR
participant Hospital PARSER_COLOR
participant CommandResult PARSER_COLOR
participant FindTaskCommand PARSER_COLOR
participant TaskList PARSER_COLOR
participant Logger LOGGER_COLOR
scale 1.5
skinparam defaultFontSize 20

User -> Parser : parseCommand(line, state)
Parser -> FindParser : execute(line, state)

alt State is MAIN_STATE
    FindParser -> Find : extract(line)
    Find -> FindParser : keyword
    FindParser -> FindPatientCommand : new FindPatientCommand(keyword)
    FindPatientCommand -> FindPatientCommand : execute()
    FindPatientCommand -> Hospital : findPatients(keyword)
    alt No matching patients found
        FindPatientCommand -> CommandResult : new CommandResult(MESSAGE_NO_MATCH)
    else Patients found
        FindPatientCommand -> CommandResult : new CommandResult(MESSAGE_SUCCESS)
    end
else State is TASK_STATE
    FindParser -> Find : extract(line)
    Find -> FindParser : keyword
    FindParser -> FindTaskCommand : new FindTaskCommand(keyword)
    FindTaskCommand -> FindTaskCommand : execute()
    FindTaskCommand -> TaskList : findTasks(keyword)
    alt No matching tasks found
        FindTaskCommand -> CommandResult : new CommandResult(MESSAGE_NO_MATCH)
    else Tasks found
        FindTaskCommand -> CommandResult : new CommandResult(MESSAGE_SUCCESS)
    end
end

alt Invalid command
    Parser -> Logger : log WARNING "Invalid command"
end

@enduml