@startuml
skinparam classAttributeIconSize 0

class FlagParser {
  - parsedFlags: HashMap
  - aliasMap: HashMap

  - generateSplitBy(String... ignoredFlags): String
  - initializeAliasMap(): void
  - parse(String argumentString, String splitBy): void
  - resolveAlias(String flag): String
  + hasFlag(String flag): boolean
  + validateRequiredFlags(String... requiredFlags): void
  + getStringByFlag(String flag): String
  + getIndexByFlag(String flag): int
  + getIntegerByFlag(String flag): int
  + getFloatByFlag(String flag): float
  + getDateByFlag(String flag): LocalDate
}

ProgCommandFactory ..>  FlagParser : "  uses"
WaterCommandFactory ..>  FlagParser : "  uses"
MealCommandFactory ..>  FlagParser : "  uses"

@enduml