@startuml
abstract class Command {
    + {abstract} execute(ProgrammeList, History): CommandResult
}

abstract class HistoryCommand {
    + execute(ProgrammeList, History): CommandResult
}

class WeeklySummaryCommand {
    + execute(ProgrammeList, History): CommandResult
}

class ViewHistoryCommand {
    - date: LocalDate
    + execute(ProgrammeList, History): CommandResult
}


Command <|-- HistoryCommand
HistoryCommand <|-- WeeklySummaryCommand
HistoryCommand <|-- ViewHistoryCommand

@enduml