@startuml

!include .SequenceDiagram.config
hide footbox

actor CEG_Student

participant ListCommandsCommand as LCC
participant UI as UI

CEG_Student -> LCC: execute (userInputString)

activate LCC

LCC -> UI: printCommandsList()
activate UI

UI --> LCC:  display list of commands
deactivate UI

LCC --> CEG_Student
deactivate LCC

@enduml