@startuml

hide footbox

actor CEG_Student

participant ":ListUniCoursesCommand" as ListUniCoursesCommand
participant ":Command" as Command
participant ":UI" as UI

CEG_Student -> ListUniCoursesCommand : execute(userInput: String)
activate ListUniCoursesCommand

ListUniCoursesCommand -> Command : createJsonObject()
activate Command

opt inputStream is null
    Command -> Command: throw new IOException()
end

Command --> ListUniCoursesCommand: jsonObject : JsonObject
deactivate Command

ListUniCoursesCommand -> ListUniCoursesCommand : getPuName(userInput: String)
activate ListUniCoursesCommand

opt puName is empty
    ListUniCoursesCommand -> ListUniCoursesCommand : throw new IllegalArgumentException
end
return puName : String

ListUniCoursesCommand -> ListUniCoursesCommand : getUniCourses(...)
activate ListUniCoursesCommand

ListUniCoursesCommand -> ListUniCoursesCommand : findUniversityName(...)
activate ListUniCoursesCommand
loop for each universityName in universityNames
    opt universityName.toLowerCase().equals(lowerCasePuName)
    return universityName : String
    end
end

alt universityName == null
    ListUniCoursesCommand -> ListUniCoursesCommand : handleUnknownUniversity(...)
    activate ListUniCoursesCommand
    return
        else else
        ListUniCoursesCommand -> ListUniCoursesCommand : listCourses(...)
        activate ListUniCoursesCommand
            loop for courseArray.size()
            ListUniCoursesCommand -> UI : printListUniCoursesCommand(...)
            activate UI
            return print course details
            end
        return
    end
return

ListUniCoursesCommand --> CEG_Student
deactivate ListUniCoursesCommand

@enduml