@startuml
hide footbox

participant ":Main" as Main
participant ":ListCommand" as ListCommand
participant ":EventList" as EventList

Main -> ListCommand:  execute()
activate ListCommand


ListCommand -> EventList : getListSize()
activate EventList
EventList --> ListCommand
deactivate EventList

loop for each event in EventList
    ListCommand -> EventList : getEvent(i)
    activate EventList
    EventList --> ListCommand
    deactivate EventList
end loop

ListCommand --> Main : outputMessage
deactivate ListCommand


deactivate Main
@enduml