@startuml

hide footbox

actor CEG_Student
participant ":ListSchoolCommand" as ListSchoolCommand
participant ":Command" as Command
participant ":IOException" as IOException

CEG_Student -> ListSchoolCommand: execute (userInput:String)
activate ListSchoolCommand

ListSchoolCommand -> Command: createJsonObject()
activate Command

opt inputStream is null
    Command -> IOException: throw new IOException()
end

Command --> ListSchoolCommand: JsonObject
deactivate Command

ListSchoolCommand -> ListSchoolCommand: displaySchoolList (jsonObject:JsonObject)
activate ListSchoolCommand

loop for each PU Name in PU Names
    ListSchoolCommand --> CEG_Student: System.out.println(universityName)
end

ListSchoolCommand --> ListSchoolCommand
deactivate ListSchoolCommand

ListSchoolCommand --> CEG_Student
deactivate ListSchoolCommand
@enduml
