@startuml
!include style.puml
hide footbox

participant ":MarkParticipantCommand" as markCommand  
participant ":EventList" as eventList  
participant "event:Event" as event  
participant "participant:Participant" as participant  

[-> markCommand : execute()
activate markCommand  

markCommand -> eventList : getEventByName(eventName)
activate eventList  

eventList --> markCommand : event:Event
deactivate eventList  

markCommand -> event : markParticipantByName(participantName)
activate event  

event -> event : getParticipantByName(participantName)
activate event  

return participant:Participant

event -> participant : setPresent(isToMark)
activate participant  

return

return

return

@enduml