@startuml
!include style.puml
hide footbox

participant ":Main" as main
participant ":MarkEventCommand" as markCommand COMMAND_COLOUR
participant ":EventList" as eventList EVENT_COLOUR
participant ":Event" as event EVENT_COLOUR

main -> markCommand : execute()
activate markCommand COMMAND_COLOUR

markCommand -> eventList : getEventByName(String)
activate eventList EVENT_COLOUR

eventList --> markCommand : eventToMark : Event
deactivate eventList

markCommand -> event : setDone(boolean)
activate event EVENT_COLOUR

event --> markCommand
deactivate event

markCommand --> main
deactivate markCommand
@enduml
