@startuml
!include style.puml

participant ":Main" as main
participant ":MarkEventCommand" as markCommand COMMAND_COLOUR
participant ":EventList" as eventList EVENT_COLOUR
participant ":Event" as event EVENT_COLOUR

main -> markCommand : execute()
activate markCommand

markCommand -> eventList : getEventByName(String)
activate eventList

eventList --> markCommand : eventToMark : Event
deactivate eventList

markCommand -> event : setDone(boolean)
activate event

event --> markCommand
deactivate event

markCommand --> main
deactivate markCommand
@enduml
