@startuml
!include style.puml

participant ":Main" as main
participant ":MarkParticipantCommand" as markCommand COMMAND_COLOUR
participant ":EventList" as eventList EVENT_COLOUR
participant "event:Event" as event EVENT_COLOUR
participant "participant:Participant" as participant EVENT_COLOUR

main -> markCommand : execute()
activate markCommand COMMAND_COLOUR

markCommand -> eventList : getEventByName(String)
activate eventList EVENT_COLOUR

eventList --> markCommand : event : Event
deactivate eventList EVENT_COLOUR

markCommand -> event : markParticipantByName(String)
activate event EVENT_COLOUR

event -> event : getParticipantByName(String)
activate event EVENT_COLOUR

return participant : Participant

event -> participant : setPresent(boolean)
activate participant EVENT_COLOUR

return

return

markCommand --> main
deactivate markCommand
@enduml