@startuml
abstract class Command {
    + {abstract} execute(ProgrammeList, History): CommandResult
}

abstract class MealCommand {
    # date: LocalDate
    + execute(ProgrammeList, History): CommandResult
}

class AddMealCommand {
    - mealName: String
    - calories: int
    + execute(ProgrammeList, History): CommandResult
}

class DeleteMealCommand {
    - mealIndex: int
    + execute(ProgrammeList, History): CommandResult
}

class ViewMealCommand {
    + execute(ProgrammeList, History): CommandResult
}

Command <|-- MealCommand
MealCommand <|-- AddMealCommand
MealCommand <|-- DeleteMealCommand
MealCommand <|-- ViewMealCommand

@enduml
