@startuml

skinparam classAttributeIconSize 0

abstract class MealCommand {
    # date: LocalDate
    + execute(History): CommandResult
}

class AddMealCommand {
    - mealName: String
    - calories: int
    + execute(History): CommandResult
}

class DeleteMealCommand {
    - indexMealToDelete: int
    + execute(History): CommandResult
}

class ViewMealCommand {
    + execute(History): CommandResult
}

MealCommand <|-- AddMealCommand
MealCommand <|-- DeleteMealCommand
MealCommand <|-- ViewMealCommand

@enduml
