@startuml
'https://plantuml.com/class-diagram

class Main {
}

Main --> "1" Ui : ui
Main --> "1" EventList : events
Main ..> Parser
Main ..> Command

class Ui {
}

Ui ..> Command

class Parser {
}

Parser ..> Command

abstract class Command {
}

Command <|-- AddCommand
Command <|-- ExitCommand
Command <|-- ListCommand
Command <|-- XYZCommand

Command ..> EventList

class EventList {
}

EventList *--> "*" Event

Event *--> "*" Participant

@enduml