@startuml
skinparam classAttributeIconSize 0
hide circle

class ParserUtils {
  + <u> splitArguments(String argumentString): String[]
  + <u>parseInteger(String intString): int
  + <u>parseFloat(String floatString): float
  + <u>parseIndex(String indexString): int
  + <u>parseDate(String dateString): LocalDate
}

ParserUtils ..> ParserException
ParserUtils ..> Utils

@enduml
