@startuml
skinparam classAttributeIconSize 0

class CommandFactory {
  - ProgCommandFactory progFactory
  - MealCommandFactory mealFactory
  - WaterCommandFactory waterFactory
  - HistoryCommandFactory historyFactory

  + createCommand(String commandString, String argumentString): Command
}

class HistoryCommandFactory {
  - <u>COMMAND_WORD: String

  + parse(String argumentString): Command
  + prepareViewHistoryCommand(String argumentString): Command
  + preparePersonalBestCommand(String argumentString): Command
  + prepareDeleteHistoryCommand(String argumentString): Command
}

class MealCommandFactory {
  - <u>COMMAND_WORD: String

  + parse(String argumentString): Command
  + prepareAddCommand(String argumentString): Command
  + prepareDeleteCommand(String argumentString): Command
  + prepareViewCommand(String argumentString): Command
}

class ProgCommandFactory {
  - <u>COMMAND_WORD: String

  + parse(String argumentString): Command
  - prepareCreateCommand(String argumentString): CreateProgrammeCommand
  - prepareViewCommand(String argumentString): ViewProgrammeCommand
  - prepareStartCommand(String argumentString): StartProgrammeCommand
  - prepareDeleteCommand(String argumentString): DeleteProgrammeCommand
  - prepareLogCommand(String argumentString): LogProgrammeCommand
  - prepareEditCommand(String argumentString): EditProgrammeCommand
  - prepareEditExerciseCommand(FlagParser flagParser): EditExerciseProgrammeCommand
  - prepareCreateExerciseCommand(FlagParser flagParser): CreateExerciseProgrammeCommand
  - prepareDeleteExerciseCommand(FlagParser flagParser): DeleteExerciseProgrammeCommand
  - prepareCreateDayCommand(FlagParser flagParser): CreateDayProgrammeCommand
  - prepareDeleteDayCommand(FlagParser flagParser): DeleteDayProgrammeCommand
  - parseDay(String dayString): Day
  - parseExercise(String argumentString): Exercise
  - parseExerciseUpdate(String argumentString): ExerciseUpdate
}

class WaterCommandFactory {
  - <u>COMMAND_WORD: String

  + parse(String argumentString): Command
  - prepareAddCommand(String argumentString): AddWaterCommand
  - prepareDeleteCommand(String argumentString): DeleteWaterCommand
  - prepareViewCommand(String argumentString): ViewWaterCommand
}

class Parser {
  - CommandFactory commandFactory
  + parse(String fullCommand): Command
}



Parser "1" --> "1" CommandFactory : uses
CommandFactory "1" *-- "1" ProgCommandFactory : creates
CommandFactory "1" *-- "1" MealCommandFactory : creates
CommandFactory "1" *-- "1" WaterCommandFactory : creates
CommandFactory "1" *-- "1" HistoryCommandFactory : creates

@enduml
