@startuml
skinparam classAttributeIconSize 0
left to right direction

class Parser {
  - logger: Logger
  - scanner: Scanner
  - mapperUI: UI
  + getUserInput(): String
  + processUserInput(userInput: String, storage: Storage): void
}

class UI {
  + displayExitMessage(): void
}

class Storage

class AddCoursesCommand {
  + execute(input: String, storage: Storage): void
}

class DeleteCoursesCommand {
  + execute(input: String, storage: Storage): void
}

class CompareMappedCommand {
  + execute(input: String, storage: Storage): void
}

class FilterCoursesCommand {
  + execute(input: String): void
}

class ListSchoolCommand {
  + execute(input: String): void
}

class ListCommandsCommand {
  + execute(input: String): void
}

class HelpCommand {
  + execute(input: String): void
}

Parser --> UI : "1"
Parser --> Storage : "1"
Parser --> AddCoursesCommand : "1..*"
Parser --> DeleteCoursesCommand : "1..*"
Parser --> CompareMappedCommand : "1..*"
Parser --> FilterCoursesCommand : "1..*"
Parser --> ListSchoolCommand : "1..*"
Parser --> ListCommandsCommand : "1..*"
Parser --> HelpCommand : "1..*"

AddCoursesCommand --> Storage : "Uses"
DeleteCoursesCommand --> Storage : "Uses"
CompareMappedCommand --> Storage : "Uses"

@enduml
