@startuml
!include style.puml

hide circle
skinparam ClassAttributeIconSize  0

class Parser {
    +parseCommand(command : String) : Command
    +parseAddCommand(input : String, commandParts : String) : Command
    +parseRemoveCommand(input : String, commandParts : String) : Command
    +parseEditCommand(input : String, commandParts : String) : Command
    +parseFilterCommand(input : String, commandParts : String) : Command
    +parseFindCommand(input : String, commandParts : String) : Command
    +parseMarkCommand(input : String, commandParts : String) : Command
    +parseRemoveCommand(input : String, commandParts : String) : Command
    +parseSortCommand(input : String, commandParts : String) : Command
}

Main ..> Parser
Parser ..> Command

@enduml