@startuml
object ProgrammeList {

}

object Programme {

}

object Day {

}

object Exercise {
}

ProgrammeList --> Programme : contains
Programme --> Day : contains
Day --> Exercise : contains
@enduml
