@startuml
skinparam classAttributeIconSize 0
hide circle

class ProgrammeCommandFactory {
  - <u> COMMAND_WORD: String

  + parse(String argumentString): Command
  - prepareCreateCommand(String argumentString): CreateProgrammeCommand
  - prepareViewCommand(String argumentString): ViewProgrammeCommand
  - prepareStartCommand(String argumentString): StartProgrammeCommand
  - prepareDeleteCommand(String argumentString): DeleteProgrammeCommand
  - prepareLogCommand(String argumentString): LogProgrammeCommand
  - prepareEditCommand(String argumentString): EditProgrammeCommand
  - prepareEditExerciseCommand(FlagParser flagParser): EditExerciseProgrammeCommand
  - prepareCreateExerciseCommand(FlagParser flagParser): CreateExerciseProgrammeCommand
  - prepareDeleteExerciseCommand(FlagParser flagParser): DeleteExerciseProgrammeCommand
  - prepareCreateDayCommand(FlagParser flagParser): CreateDayProgrammeCommand
  - prepareDeleteDayCommand(FlagParser flagParser): DeleteDayProgrammeCommand
  - parseDay(String dayString): Day
  - parseExercise(String argumentString): Exercise
  - parseExerciseUpdate(String argumentString): ExerciseUpdate
}

ProgrammeCommandFactory "1          " --> "1" Command : "creates"

ProgrammeCommandFactory "1       " -->  "1" FlagParser : "creates"

ProgrammeCommandFactory ..> ParserUtils
ProgrammeCommandFactory ..> FlagDefinitions
ProgrammeCommandFactory ..> ProgrammeException
ProgrammeCommandFactory ..> FlagException

ProgrammeCommandFactory ..> Day
ProgrammeCommandFactory ..> Exercise
ProgrammeCommandFactory ..> ExerciseUpdate


@enduml
