@startuml
!include style.puml
hide footbox

participant ":RemoveCommand" as command COMMAND_COLOUR
participant ":EventList" as eventList EVENT_COLOUR
participant "eventList:ArrayList<Event>" as list EVENT_COLOUR
participant "event:Event" as event EVENT_COLOUR

group sd Remove event
    activate command COMMAND_COLOUR

    command -> eventList : removeEvent(eventName)
    activate eventList EVENT_COLOUR
    loop for event in eventList
        eventList -> event : getName()
        activate event EVENT_COLOUR
        return :String

        opt event exists in eventList
            eventList -> list : remove(event)
            activate list EVENT_COLOUR
            destroy event
            return
            eventList --> command : :boolean
        end
    end
    return :boolean
end

@enduml