@startuml
!include style.puml
hide footbox

participant ":RemoveCommand" as command  
participant ":EventList" as eventList  

group sd Remove participant
    activate command  
    command -> eventList : removeParticipantFromEvent(participantName,\n eventName)
    activate eventList  

    eventList -> eventList : getEventByName()
    activate eventList  

    return event:Event

    alt event not found
        eventList --> command : :boolean
    else else
        ref over eventList : Remove participant from event
        eventList --> command : :boolean
    end
end


@enduml