@startuml
!include style.puml
hide footbox

participant ":RemoveCommand" as command  
participant ":EventList" as eventList  
participant "eventList:ArrayList<Event>" as list  
participant "event:Event" as event  

group sd Remove event
    activate command  

    command -> eventList : removeEvent(eventName)
    activate eventList  
    loop for event in eventList
        eventList -> event : getName()
        activate event  
        return :String

        opt event exists in eventList
            eventList -> list : remove(event)
            activate list
            destroy event
            note right of event
                The lifeline does not end
                here due to a PlantUML
                limitation.            
            end note
            return
        end
    end
    return :boolean
end

@enduml