@startuml

actor User
participant FitTrack
participant Parser
participant TrainingSession
participant Ui
participant PullUpStation
participant ShuttleRunStation
participant SitAndReachStation
participant SitUpStation
participant StandingBroadJumpStation
participant WalkAndRunStation

User -> FitTrack: add session name
activate FitTrack

FitTrack -> Parser: parse(...)
activate Parser

Parser -> TrainingSession: new TrainingSession(currentTime, description, user)
activate TrainingSession

' Initialize exercise stations
TrainingSession -> TrainingSession: initialiseExerciseStations()
activate TrainingSession

TrainingSession -> PullUpStation: new PullUpStation()
activate PullUpStation
return
deactivate PullUpStation

TrainingSession -> ShuttleRunStation: new ShuttleRunStation()
activate ShuttleRunStation
return
deactivate ShuttleRunStation

TrainingSession -> SitAndReachStation: new SitAndReachStation()
activate SitAndReachStation
return
deactivate SitAndReachStation

TrainingSession -> SitUpStation: new SitUpStation()
activate SitUpStation
return
deactivate SitUpStation

TrainingSession -> StandingBroadJumpStation: new StandingBroadJumpStation()
activate StandingBroadJumpStation
return
deactivate StandingBroadJumpStation

TrainingSession -> WalkAndRunStation: new WalkAndRunStation()
activate WalkAndRunStation
return
deactivate WalkAndRunStation

TrainingSession --> Parser
deactivate TrainingSession

Parser -> FitTrack: sessionList.add(TrainingSession)

activate FitTrack
return

Parser -> Ui: printAddedSession(sessionList)
activate Ui
Ui --> Parser
deactivate Ui

Parser --> FitTrack

deactivate Parser
@enduml
