@startuml
title Sequence Diagram for "delete <index of a training session>" Command

actor User
participant FitTrack
participant Parser
participant Ui

User -> FitTrack: User inputs delete command
activate FitTrack
FitTrack -> Parser: parse(...)
activate Parser

Parser --> FitTrack: sessionList.get(indexToDelete)

FitTrack -> Parser: sessionToDelete

Parser --> FitTrack: sessionList.remove(indexToDelete)

Parser -> Ui: printDeletedSession(sessionList, sessionToDelete)
activate Ui

note over Ui
    Print DELETE_SESSION_MESSAGE
    Print sessionDescription
end note
Ui -> Ui: printSessionCount(sessionList)
activate Ui
Ui --> Ui
deactivate Ui
Ui --> Parser
deactivate Ui
Parser --> FitTrack
deactivate Parser
deactivate FitTrack

@enduml
