@startuml
title Sequence Diagram for "view <Training Session Index>" Command

actor User

User -> FitTrack: Training Sessions Command
activate FitTrack
    FitTrack -> Parser: parse(...)
        activate Parser
            Parser -> Ui: printSessionView(...)
                activate Ui
                    Ui -> FitTrack : sessionList.get(...)
                        activate FitTrack
                            FitTrack --> Ui: TrainingSession
                        deactivate FitTrack
                    Ui -> TrainingSession: TrainingSession.viewSession()
                        activate TrainingSession
                            note over TrainingSession
                            Print TrainingSession description and datetime
                            end note
                            loop for each ExerciseStation
                                TrainingSession -> ExerciseStation: exercise.getPoints(user)
                                activate ExerciseStation
                                    ExerciseStation -> Calculator: calculatePoints()
                                    activate Calculator
                                    Calculator --> ExerciseStation: calculatePoints
                                    deactivate Calculator
                                ExerciseStation --> TrainingSession: exercisePoint
                                TrainingSession -> ExerciseStation: exercise.getName()
                                ExerciseStation --> TrainingSession: exerciseName
                                note over TrainingSession
                                Print exerciseName and exercise
                                end note
                            end loop
                            note over TrainingSession
                            Print totalPoints and overallAward
                            end note
                            ExerciseStation --> TrainingSession
                            deactivate ExerciseStation
                            TrainingSession --> Ui
                        deactivate TrainingSession
                Ui --> Parser
                deactivate Ui
            Parser --> FitTrack
        deactivate Parser
    FitTrack --> User
deactivate FitTrack

'activate FitTrack
'FitTrack -> Parser: parse(...)
'activate Parser
'Parser -> Ui: printSessionList(...)
'
'activate Ui
'
'alt sessionList.isEmpty()
'    note over Ui
'        Print LIST_SESSION_EMPTY_MESSAGE
'    end note
'else !sessionList.isEmpty()
'    note over Ui
'        Print LIST_SESSION_MESSAGE
'    end note
'    loop for each in sessionList
'        Ui --> FitTrack: sessionList.get(sessionIndex)
'        activate FitTrack
'        FitTrack --> Ui: TrainingSession
'        deactivate FitTrack
'
'        Ui -> TrainingSession: getSessionDescription()
'        activate TrainingSession
'        TrainingSession --> Ui: sessionDescription
'        deactivate TrainingSession
'
'        note over Ui
'            Print sessionDescription
'        end note
'    end
'    Ui -> Ui: printSessionCount()
'    activate Ui
'    Ui --> Ui
'    deactivate Ui
'end
'Ui --> Parser
'deactivate Ui
'Parser --> FitTrack
'deactivate Parser
'FitTrack --> User
'deactivate FitTrack

@enduml
