@startuml

participant ":Parser" as parser
participant ":TrainingSession" as ts
participant ":ExerciseStation" as es
skinparam style strictuml

parser -> ts: editExercise(Exercise, reps)
activate ts

ts -> ts: processReps(Exercise, reps)
activate ts
ts --> ts: actualReps
deactivate ts

ts -> es: setPerformance(actualReps)
activate es
es --> ts
deactivate es

ts -> es: getPoints(user)
activate es
es --> ts: points
deactivate es

ts --> parser:
deactivate ts

@enduml
