@startuml

!include style.puml

class StateManager LOGIC_COLOR{
    - State currentState
    + StateManager()
    + getCurrentState(): State
    + setCurrentState(State currentState): void
    + changeState(StateType state): void
    + getState(): StateType
    + runState(String commandInput, Command command, Hospital hospital): CommandResult
    + runMainState(String commandInput, Command command, Hospital hospital): CommandResult
    + runTaskState(String commandInput, Command command, Hospital hospital): CommandResult
}

class State LOGIC_COLOR{
    - StateType currentStage
    + State()
    + State(StateType state)
    + getState(): StateType
    + setState(StateType state): void
}

enum StateType LOGIC_COLOR{
    MAIN_STATE
    TASK_STATE
}

class CommandResult COMMAND_COLOR{
    - feedbackToUser: String
    + CommandResult(String feedbackToUser)
    + getFeedbackToUser(): String
}

StateManager .left.> "0..1" State
State --> StateType
StateManager --> CommandResult

@enduml
