@startuml
!include style.puml

actor ":User" as U
participant ":Main" as M LOGIC_COLOR
participant ":UI" as UI UI_COLOR
participant ":Parser" as P PARSER_COLOR
participant ":State" as S LOGIC_COLOR_T2
participant ":Command" as C COMMAND_COLOR

U -> M: Execute main()
M -> UI: readCommand()
UI --> M: commandInput

alt MAIN_STATE
    M -> P: parseCommand(commandInput, MAIN_STATE)
    P -> S: getState()
    S --> P: MAIN_STATE
    P -> C: create AddPatientCommand
    C --> M: execute()

else TASK_STATE
    M -> P: parseCommand(commandInput, TASK_STATE)
    P -> S: getState()
    S --> P: TASK_STATE
    P -> C: create AddTaskCommand
    C --> M: execute()

end

M -> UI: showMessage(commandResult)

@enduml
