@startuml
!include style.puml
hide circle
skinparam ClassAttributeIconSize 0

allowmixing

    class Storage {
        - filePath : String
        + Storage(filePath : String)
        + void saveEvents(EventList events) throws IOException
        + loadEvents(EventList events) : void
        - isValidFilePath(String filePath) : boolean
        - isTestEnvironment() : boolean
    }

class Main
class EventList
class Parser

Storage ..> EventList : saves/loads >
Parser <.. Storage : < adopts
Main .> Storage : invokes >

@enduml
