@startuml
!include style.puml
hide footbox

Participant ":Main" as main
Participant ":Storage" as storage 
Participant ":EventList" as eventList 
Participant "event:Event" as event 

group sd Saving of participant data
main -> storage : saveParticipants(EventList)
activate storage 
storage -> eventList : getList()
activate eventList 
return :ArrayList<Event>

loop for event in event list

storage -> storage : saveEventParticipants(...)
activate storage 

storage -> event : getParticipantsList()
activate event 
return :ArrayList<Participant>

return

end

return

end

@enduml