@startuml
!include style.puml
hide footbox

Participant ":Main" as main
Participant ":Storage" as storage 
Participant ":EventList" as event 


group sd Saving of event data
main -> storage : saveEvents(EventList)
activate storage 
storage -> event : getList()
activate event 
return :ArrayList<Event>

storage --> main
deactivate storage
end

@enduml