@startuml
!include style.puml
allowmixing

package storage {
    class Storage {
        - filePath : String
        + Storage(filePath : String)
        + void saveEvents(EventList events) throws IOException
        + loadEvents(EventList events) : void
        - isValidFilePath(String filePath) : boolean
        - isTestEnvironment() : boolean
    }
}

rectangle Main
rectangle Event EVENT_COLOUR
rectangle Parser PARSER_COLOUR

Storage ..> Event : saves/loads >
Parser <.. Storage : < adopts
Main .> Storage : invokes >

@enduml
