@startuml
!include style.puml
hide footbox

Participant ":Main" as main
Participant ":Storage" as storage 
Participant ":FileParser" as parser 
Participant ":EventList" as events 


group sd Loading of event data
main -> storage : loadEvents(EventList)
activate storage 

create parser
storage -> parser : FileParser()
activate parser 
return

storage -> parser : parseEventFile(String)
activate parser 

loop for line in file
parser -> parser : parseEventFileLine(...)
activate parser 

parser -> events : addEvent(...)
activate events 

return

return

end

return

return

end

@enduml