@startuml
!include style.puml
hide footbox

Participant ":Main" as main
Participant ":Storage" as storage STORAGE_COLOUR
Participant ":EventList" as event EVENT_COLOUR


group sd Saving of event data
main -> storage : saveEvents(EventList)
activate storage STORAGE_COLOUR
storage -> event : getList()
activate event EVENT_COLOUR
return :ArrayList<Event>

storage --> main
deactivate storage
end

@enduml