@startuml
!include style.puml
hide footbox

Participant ":Main" as main
Participant ":Storage" as storage STORAGE_COLOUR
Participant ":EventList" as eventList EVENT_COLOUR
Participant "event:Event" as event EVENT_COLOUR

group sd Saving of participant data
main -> storage : saveInfo(EventList)
activate storage STORAGE_COLOUR

loop for event in event list

storage -> eventList : getList()
activate eventList EVENT_COLOUR
return :ArrayList<Event>

loop for participant in participant list

storage -> event : getParticipantList()
activate event EVENT_COLOUR
return :ArrayList<Participant>

end

loop for item in participant list

storage -> event : getItemList()
activate event EVENT_COLOUR
return :ArrayList<Item>

end

end

return

end


@enduml