@startuml
skinparam classAttributeIconSize 0

!define CLASS(x) class x

class Ui {
    - <u>ERROR_HEADER: String
    - <u>LINE_CHAR: String
    - <u>LINE_LENGTH: int
    - in: Scanner
    - out: PrintStream

    + readCommand(): String
    + showLine(): void
    + showMessage(String msg): void
    + showMessage(Exception e): void
    + showMessage(CommandResult result): void
    + showWelcome(): void
    + showFarewell(): void
    + showFirstTime(): void
}

class CommandResult {
  - message: String

  + getMessage(): String
}

Ui ..> Scanner
Ui ..> PrintStream
Ui ..> CommandResult

@enduml