@startuml
!include style.puml
hide footbox

participant ":ViewCommand" as command
participant "eventToView:Event" as event
participant "item:Item" as item

group sd view items
activate command
    command -> command : getItems(eventToView : Event)
    activate command

    command -> event : getItemsList()
    activate event

    return items : ArrayList<Item>

    loop for item in items
        command -> item : toString()
        activate item
        return :String
    end

    return :String
end
@enduml
