@startuml
actor User
participant "ViewWaterCommand" as ViewCmd
participant "DailyRecord" as DailyRec

ViewCmd -> DailyRec: getWaterFromRecord()
activate ViewCmd
activate DailyRec
DailyRec --> ViewCmd: Water object
deactivate DailyRec

deactivate ViewCmd
destroy ViewCmd
@enduml