@startuml
!include style.puml
hide footbox

participant ":ViewCommand" as command COMMAND_COLOUR
participant "eventToView:Event" as event EVENT_COLOUR
participant "item:Item" as item EVENT_COLOUR

group sd view items
activate command COMMAND_COLOUR
    command -> command : getItems(Event)
    activate command COMMAND_COLOUR

    command -> event : getItemsList()
    activate event EVENT_COLOUR

    return items : ArrayList<Item>

    loop for item in items
        command -> item : toString()
        activate item EVENT_COLOUR
        return :String
    end

    return :String
end
@enduml
