@startuml
!include style.puml
hide footbox

participant ":ViewCommand" as command  
participant ":EventList" as eventList  

[-> command : execute()
activate command  

command -> eventList : getEventByName(eventName)
activate eventList  

return eventToView:Event

alt eventToView not found
    command -->[ : Invalid event
else isViewingParticipants is true
    ref over command, eventList: View participants
else else
    ref over command, eventList: View items
end

return

@enduml
