@startuml

participant "ViewWaterCommand" as ViewCmd
participant "DailyRecord" as DailyRec

create ViewCmd
-> ViewCmd : ViewWaterCommand()
ViewCmd -> DailyRec: getWaterFromRecord()
activate ViewCmd
activate DailyRec
DailyRec --> ViewCmd: Water object
deactivate DailyRec

deactivate ViewCmd
<-- ViewCmd
destroy ViewCmd
@enduml