@startuml
!include style.puml
hide footbox

participant ":Main" as main
participant ":ViewCommand" as command
participant ":EventList" as eventList

main -> command : execute()
activate command

command -> eventList : getEventByName(eventName : String)
activate eventList

return eventToView : Event

alt eventToView == null
    command --> main : Invalid event
else isViewingParticipants
    ref over command, eventList: view participants
else else
    ref over command, eventList: view items
end

return

@enduml
