@startuml

class Water {
    - waterList : ArrayList<Float>
    + Water(): void
    + isEmpty() : boolean
    + addWater(float water) : void
    + deleteWater(int index) : float
    + getWaterList() : ArrayList<Float>
}

@enduml