@startuml
skinparam classAttributeIconSize 0
abstract class WaterCommand {
    # date: LocalDate
    + execute(ProgrammeList, History): CommandResult
}

class AddWaterCommand {
    -amount: int
    + execute(ProgrammeList, History): CommandResult
}

class DeleteWaterCommand {
    - waterIndex: int
    + execute(ProgrammeList, History): CommandResult
}

class ViewWaterCommand {
    + execute(ProgrammeList, History): CommandResult
}

WaterCommand <|-- AddWaterCommand
WaterCommand <|-- DeleteWaterCommand
WaterCommand <|-- ViewWaterCommand

@enduml
