@startuml

skinparam classAttributeIconSize 0

abstract class WaterCommand {
    # date: LocalDate
    + execute(History): CommandResult
}

class AddWaterCommand {
    - amount: int
    + execute(History): CommandResult
}

class DeleteWaterCommand {
    - waterIndex: int
    + execute(History): CommandResult
}

class ViewWaterCommand {
    + execute(History): CommandResult
}

WaterCommand <|-- AddWaterCommand
WaterCommand <|-- DeleteWaterCommand
WaterCommand <|-- ViewWaterCommand

@enduml
