@startuml
title AddCommand Sequence Diagram
hide footbox

participant ":User"
participant ":AddCommand"
participant ":uiCommand"
participant ":Internship"
participant ":InternshipList"


":User"->":AddCommand":execute(args)
activate ":AddCommand" #red
":AddCommand"-->":uiCommand":clearInvalidFlags()
activate ":uiCommand" #green
":AddCommand"->":AddCommand" : Initialize variables

loop Process each argument in args
  ":AddCommand" -> ":AddCommand" : process flag and data
  alt flag is valid
    alt data is present
      ":AddCommand" -> ":AddCommand" : set data
    else
      ":AddCommand" -> ":uiCommand" : addInvalidFlag(flag)
      activate ":uiCommand" #green
      deactivate ":uiCommand"
    end
  else
    ":AddCommand" -> ":uiCommand" : addInvalidFlag(flag)
    activate ":uiCommand" #green
    deactivate ":uiCommand"
  end
end

alt invalid flags found
  ":AddCommand"->":uiCommand": printInvalidFlags()
  activate ":uiCommand" #green
  deactivate ":uiCommand"
else all required flags present
  ":AddCommand" -> ":Internship" **: new Internship(role, company, startDate, endDate)
  activate ":Internship" #blue
  ":AddCommand"-> ":InternshipList": addInternship(newInternship)
  activate ":InternshipList" #aquamarine
  deactivate ":Internship"
  deactivate ":InternshipList"
  ":AddCommand" -> ":uiCommand": showEditedInternship(newInternship, "add")
  deactivate ":uiCommand"
end

@enduml