@startuml
Title loadFromFile
hide footbox
participant ":User"
participant ":EasInternship"
participant ":Storage"
participant ":InternshipList"
participant ":Internship"

":User"->":EasInternship": start program
activate ":EasInternship" #green
":EasInternship"->":InternshipList": new ":InternshipList"()
activate ":InternshipList" #aquamarine
":EasInternship"->":Storage": loadFromFile(internshipList)
activate ":Storage" #orange

loop for each line in file
    ":Storage"-> ":Internship" : new ":Internship"(role, company, startDate, endDate)
    activate ":Internship" #blue
    ":Internship"->":InternshipList": addInternship
    ":Storage" -> ":Internship" :setSkills(skills)
    ":Storage" -> ":Internship" : setStatus(status)
    deactivate ":Internship"

    ":Storage" -> ":Storage": parseDeadlines(deadlineString, internshipId)
        activate ":Storage" #orange

        ":Storage" -> ":Deadline": new Deadline (description, date)
        activate ":Deadline" #purple
        deactivate ":Deadline"
        deactivate ":Storage"

        ":Internship" -> ":Deadline" : addDeadline(deadline)
end
deactivate ":Storage"
@enduml

