@startuml
loop Command Processing Loop

    FinanceBuddy -> Logic : matchCommand(command, commandArguments)
    activate Logic

    alt command is "list /from date /to date"
        Logic -> DateParser : parse(commandArguments.get("/from"))
        activate DateParser
        DateParser --> Logic : LocalDate (startDate)
        deactivate DateParser

        Logic -> DateParser : parse(commandArguments.get("/to"))
        activate DateParser
        DateParser --> Logic : LocalDate (endDate)
        deactivate DateParser

        Logic -> SeeAllEntriesCommand : create(startDate, endDate)
        activate SeeAllEntriesCommand
        ref over SeeAllEntriesCommand : execute command
        SeeAllEntriesCommand --> Logic

        deactivate SeeAllEntriesCommand

    else command is unknown
        Logic -> AppUi : showUnknownCommandMessage()
        activate AppUi
        AppUi --> Logic : success
        deactivate AppUi
    end

    Logic --> FinanceBuddy : command processed
    deactivate Logic
end
@enduml
