@startuml
package seedu.duke.parser {
    class DateParser {
        - formatter : DateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yy")

        + parse(dateStr : String) : LocalDate throws FinanceBuddyException
    }
}
@enduml

@startuml
package seedu.duke.parser {
    class InputParser {
        + COMMAND : String
        + ARGUMENT : String

        + parseCommands(input : String) : HashMap<String, String> throws FinanceBuddyException
    }
}
@enduml
