@startuml
Title saveToFile
hide footbox
participant ":User"
participant ":EasInternship"
participant ":Storage"
participant ":InternshipList"
participant ":Internship"

":User" -> ":EasInternship": exit program
activate ":EasInternship" #green
":EasInternship" -> ":Storage" : saveToFile(internshipList)
activate ":Storage" #orange
":Storage" -> ":InternshipList" : getAllInternships()
activate ":InternshipList" #aquamarine
":InternshipList" -> ":Storage" : List<":Internship">
deactivate ":InternshipList"

loop for each ":Internship"
":Storage"-> ":Internship" : get each attribute
activate ":Internship" #blue
":Internship" -> ":Storage" : List<Deadline>
deactivate ":Internship"
    loop for each Deadline
        ":Storage" -> Deadline : get each attribute
        activate Deadline  #teal
        deactivate Deadline
    end
end

deactivate ":Storage"
@enduml