@startuml
title SortCommand Sequence Diagram
hide footbox

":User" -> ":SortCommand": execute(args: ArrayList<String>)
activate ":SortCommand" #red

alt args are empty
    ":SortCommand" -> ":InternshipList": listInternshipsNotSorted()
    activate ":InternshipList" #green
    deactivate ":InternshipList" #green
else args are not empty
    ":SortCommand" -> ":SortCommand": get first argument (sortOption)

    alt sortOption == "role"
        ":SortCommand" -> ":InternshipList": listInternshipsSortedByRole()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green
    else sortOption == "duration"
        ":SortCommand" -> ":InternshipList": listInternshipsSortedByDuration()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green
    else sortOption == "deadline"
        ":SortCommand" -> ":InternshipList": listInternshipsSortedByDeadline()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green
    else sortOption == "skills"
        ":SortCommand" -> ":InternshipList": listInternshipsSortedByFirstSkill()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green
    else sortOption == "status"
        ":SortCommand" -> ":InternshipList": listInternshipsSortedByStatus()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green
    else sortOption == "company"
        ":SortCommand" -> ":InternshipList": listInternshipsSortedByCompany()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green

    else sortOption == "role in favourite"
        ":SortCommand" -> ":InternshipList": listFavouriteInternshipsSortedByRole()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green
    else sortOption == "duration in favourite"
        ":SortCommand" -> ":InternshipList": listFavouriteInternshipsSortedByDuration()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green
    else sortOption == "deadline in favourite"
        ":SortCommand" -> ":InternshipList": listFavouriteInternshipsSortedByDeadline()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green
    else sortOption == "skills in favourite"
        ":SortCommand" -> ":InternshipList": listFavouriteInternshipsSortedByFirstSkill()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green
    else sortOption == "status in favourite"
        ":SortCommand" -> ":InternshipList": listFavouriteInternshipsSortedByStatus()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green
    else sortOption == "company in favourite"
        ":SortCommand" -> ":InternshipList": listFavouriteInternshipsSortedByCompany()
        activate ":InternshipList" #green
        deactivate ":InternshipList" #green

    else invalid sortOption
        ":SortCommand" -> ":UI": showOutput("Invalid sort option")
        activate ":UI" #blue
        deactivate ":UI"
    end
end

@enduml