@startuml
package seedu.duke.financial {
    abstract class FinancialEntry {
        + amount : double
        + date : LocalDate
        + description : String

        + FinancialEntry(amount : double, date : LocalDate, description : String)
        + getAmount() : double
        + getDate() : LocalDate
        + getDescription() : String
        + setAmount(amount : double) : void
        + setDescription(description : String) : void
    }

    class Expense extends FinancialEntry {
        + category : Category
        + Expense(amount : double, date : LocalDate, description : String, category : Category)
        + getCategory() : Category
        + setCategory(category : Category) : void
    }

    class Income extends FinancialEntry {
        + category : Category
        + Income(amount : double, date : LocalDate, description : String, category : Category)
        + getCategory() : Category
        + setCategory(category : Category) : void
    }
}
@enduml
