@startuml
TrainingSession -> PullUpStation : getPoints(reps)
activate PullUpStation

PullUpStation -> PullUpCalculator : calculatePoints(user.gender, user.age, reps)
activate PullUpCalculator

PullUpCalculator --> PullUpStation : return calculated points
deactivate PullUpCalculator

PullUpStation --> TrainingSession : return
deactivate PullUpStation
@enduml
