@startuml
skinparam classAttributeIconSize 0

package "ymfc.commands" {

    abstract class Command {
        # isBye: boolean
        __
        + setBye(): void
        + isBye(): boolean
        + {abstract} execute(recipes: RecipeList, ingredients: IngredientList, ui: Ui, storage: Storage): void
    }
    hide Command circle

    class AddRecipeCommand {
        - recipe: Recipe
        + {static} USAGE_EXAMPLE: String
        __
        + addNewRecipe(recipes: RecipeList, newRecipe: Recipe, ui: Ui, storage: Storage): void
        + addLoadedRecipe(recipes: RecipeList): void
    }
    hide AddRecipeCommand circle

    class AddIngredientCommand {
        - ingredient: Ingredient
        + {static} USAGE_EXAMPLE: String
        __
        + addNewIngredient(ingredients: IngredientList, newIngredient: Ingredient, ui: Ui, storage: Storage): void
        + addLoadedIngredient(ingredients: List): void
    }
    hide AddIngredientCommand circle

    class ByeCommand
    hide ByeCommand circle

    class DeleteCommand {
        - recipeName: String
        + {static} USAGE_EXAMPLE: String
    }
    hide DeleteCommand circle

    class EditCommand {
        - recipe: Recipe
        + {static} USAGE_EXAMPLE: String
    }
    hide EditCommand circle

    class FindCommand {
        - query: String
        - isByName: boolean = true
        - isByIngredient: boolean = false
        - isByStep: boolean = false
        - numMatches: int = 0
        + {static} USAGE_EXAMPLE: String
        __
        + getNumMatches(): int
        - isFoundInSteps(recipe: Recipe): boolean
        - isFoundInIngredients(recipe: Recipe): boolean
        - isQueryFoundInName(recipe: Recipe): boolean
    }
    hide FindCommand circle

    class FindIngredCommand {
        - query: String
        - numMatches: int = 0
        + {static} USAGE_EXAMPLE: String
        __
        + getNumMatches(): int
        - isQueryFoundInName(recipe: Recipe): boolean
    }
    hide FindIngredCommand circle

    class HelpCommand
    hide HelpCommand circle

    class ListCommand
    hide ListCommand circle

    class ListIngredientCommand
    hide ListIngredientCommand circle

    class SortCommand {
        - listBy: String
        + {static} USAGE_EXAMPLE: String
    }
    hide SortCommand circle

    AddRecipeCommand --u|> Command
    AddIngredientCommand --u|> Command
    ByeCommand --u|> Command
    DeleteCommand --u|> Command
    EditCommand --u|> Command
    FindCommand --u|> Command
    FindIngredCommand --u|> Command
    HelpCommand --u|> Command
    ListCommand --u|> Command
    ListIngredientCommand --u|> Command
    SortCommand --u|> Command

}

@enduml