@startuml

autoactivate on

actor User

participant "Cli" as CLI
participant "Parser" as P
participant "QuizManager" as QM

User -> CLI : readInput() (e.g., "select Loops")
CLI -> P : determineCommand("select Loops")
deactivate CLI
P -> P : processCommand("select Loops")
return
P -> QM : selectTopic("Loops")
deactivate P
QM -> QM : Starts Quiz on "Loops"
QM -> User : Quiz Start on Loops

deactivate CLI
deactivate QM
deactivate P
deactivate CLI

@enduml
