@startuml

hide circle

skinparam classAttributeIconSize 0

skinparam rectangle {
    BackgroundColor White
    BorderColor Black
    FontColor Black
}

rectangle QuizManager as QM
rectangle QuizSession as QS
rectangle TopicManager as TM
rectangle QuizResults as QR

QM *-down-> "1" QS : creates
QM *-down-\\ "1" TM : manages
QM *-down-> "1" QR : manages

rectangle Quiz as Q
rectangle Topic as T
rectangle QuizTimer as QTi

QS *-down-> "1" Q : generates
TM *--down-> "0..*" T : loads
Q *-down-> "0..1" QTi : when starts

rectangle Question as Ques
T *-down-> "0..*" Ques : contains

rectangle FillInTheBlank as FITB
rectangle Flashcard as FC
rectangle Mcq as MCQ
rectangle TrueFalse as TF

Ques <|-down- FITB : subtype
Ques <|-down- FC : subtype
Ques <|-down- MCQ : subtype
Ques <|-down- TF : subtype

rectangle storage as store

QR *--left-> "1" store : loads past results
Q *-> "1" store : saves results

Q --> "1 ..*" T : begins with


@enduml