package seedu.command;

import seedu.main.Main;

import java.util.ArrayList;
import java.util.List;

public class ByeCommand extends Command{
    public static final String COMMAND_WORD = "bye";
    public static final String COMMAND_GUIDE = "bye: End the chat.";
    public static final String[] COMMAND_MANDATORY_KEYWORDS = {};
    public static final String[] COMMAND_EXTRA_KEYWORDS = {};

    public static final String END_MESSAGE = "Closing! See you tomorrow!";
    /**
     * Executes the help command and returns a list of command guide messages.
     *
     * @return A list of strings containing the messages generated by the command execution.
     */
    @Override
    public List<String> execute() {
        List<String> messages = new ArrayList<>();

        Main.setRunning(false);

        messages.add(END_MESSAGE);


        return messages;
    }

    /**
     * Gets the mandatory keywords for the command.
     *
     * @return An array of strings containing the mandatory keywords associated with this command.
     */
    @Override
    protected String[] getMandatoryKeywords() {
        return COMMAND_MANDATORY_KEYWORDS;
    }

    /**
     * Gets the extra keywords for the command.
     *
     * @return An array of strings containing the extra keywords associated with this command.
     */
    @Override
    protected String[] getExtraKeywords() {
        return COMMAND_EXTRA_KEYWORDS;
    }

    /**
     * Gets the word for the command.
     *
     * @return A string representing the command word.
     */
    @Override
    protected String getCommandWord() {
        return COMMAND_WORD;
    }

    /**
     * Gets the guide for the command.
     *
     * @return A string representing the command guide.
     */
    @Override
    protected String getCommandGuide() {
        return COMMAND_GUIDE;
    }
}
